Repository commercetools/connect-payment-integration-adyen, pull requests merged in 2024-06, with the labels that each got.

#135 feat(klarna): remove the componentHasSubmit for all Klarna options
  enabler/src/components/payment-methods/klarna-pay-later.ts
  enabler/src/components/payment-methods/klarna-pay-now.ts
  enabler/src/components/payment-methods/klarna-pay-over-time.ts
Labels: 1 min review

#136 fix(klarna): force show pay button
  enabler/src/components/payment-methods/klarna-pay-later.ts
  enabler/src/components/payment-methods/klarna-pay-now.ts
  enabler/src/components/payment-methods/klarna-pay-over-time.ts
Labels: 1 min review, missing-jira

#139 chore(connector): Inform users on scopes and correct urls
  connect.yaml
Labels: 1 min review, missing-jira

#140 chore(connector): Inform users on scopes and correct urls
  connect.yaml
Labels: 1 min review, missing-jira

#137 chore(processor): improve dev tools
  README.md
  docker-compose.yaml
  enabler/dev-utils/session.js
  enabler/index.html
  processor/.env.template
  processor/package.json
Labels: 5 min review

#145 chore(klarna): disable klarna for certification
  enabler/dev-utils/session.js
  processor/src/services/converters/create-payment.converter.ts
  processor/src/services/converters/payment-components.converter.ts
  processor/test/services/adyen-payment.service.spec.ts
Labels: missing-jira

#150 chore: Update connect.yaml
  connect.yaml
Labels: missing-jira

#153 Revert "chore(klarna): disable klarna for certification"
  enabler/dev-utils/session.js
  processor/src/services/converters/create-payment.converter.ts
  processor/src/services/converters/payment-components.converter.ts
  processor/test/services/adyen-payment.service.spec.ts
Labels: missing-jira
